name: evernote_personal
description: A personal note-taking app inspired by Evernote.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  uuid: ^4.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/hippo.png"
  adaptive_icon_background: "#F0EEEA"
  adaptive_icon_foreground: "assets/images/hippo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
